# the whole biome tinting "system" needs a rework, when that is done i probably want to
# store biome parameters (temperature, humidity, ???), here as well and calculate tints based on that
# (currently: hardcoded in biomes.go)

# these colors are hand picked to look nice to me, very far from covering all blocks
[blocks]
"minecraft:sweet_berry_bush" = "#7d1111"
"minecraft:blue_orchid" = "#34aacf"
"minecraft:bone_block" = "#f2ece6"
"minecraft:cut_copper" = "#C6754A"
"minecraft:waxed_cut_copper" = "#C6754A"
"minecraft:cut_copper_slab" = "#C6754A"
"minecraft:waxed_cut_copper_slab" = "#C6754A"
"minecraft:cut_copper_stairs" = "#C6754A"
"minecraft:waxed_cut_copper_stairs" = "#C6754A"
"minecraft:copper_block" = "#C6754A"
"minecraft:waxed_copper_block" = "#C6754A"
"minecraft:waxed_chiseled_copper" = "#C6754A"
"minecraft:waxed_copper_grate" = "#C6754A"
"minecraft:waxed_copper_trapdoor" = "#C6754A"
"minecraft:copper_bulb" = "#C6754A"
"minecraft:waxed_copper_bulb" = "#C6754A"
"minecraft:chiseled_copper" = "#C6754A"
"minecraft:exposed_copper" = "#b87333"
"minecraft:waxed_exposed_copper" = "#b87333"
"minecraft:waxed_exposed_copper_bulb" = "#b87333"
"minecraft:weathered_copper" = "#5d967d"
"minecraft:waxed_weathered_copper" = "#5d967d"
"minecraft:waxed_weathered_chiseled_copper" = "#5d967d"
"minecraft:waxed_weathered_copper_bulb" = "#5d967d"
"minecraft:oxidized_copper" = "#70B596"
"minecraft:oxidized_copper_door" = "#70B596"
"minecraft:waxed_oxidized_copper_door" = "#70B596"
"minecraft:oxidized_copper_trapdoor" = "#70B596"
"minecraft:waxed_oxidized_copper" = "#70B596"
"minecraft:waxed_oxidized_chiseled_copper" = "#70B596"
"minecraft:waxed_oxidized_copper_grate" = "#70B596"
"minecraft:waxed_oxidized_copper_trapdoor" = "#70B596"
"minecraft:oxidized_cut_copper" = "#70B596"
"minecraft:waxed_oxidized_cut_copper" = "#70B596"
"minecraft:oxidized_cut_copper_slab" = "#70B596"
"minecraft:waxed_oxidized_cut_copper_slab" = "#70B596"
"minecraft:oxidized_cut_copper_stairs" = "#70B596"
"minecraft:waxed_oxidized_cut_copper_stairs" = "#70B596"
"minecraft:oxidized_copper_bulb" = "#70B596"
"minecraft:waxed_oxidized_copper_bulb" = "#70B596"
"minecraft:birch_leaves" = "#1e4621"
"minecraft:jungle_leaves" = "#1C7402"
"minecraft:sand" = "#c2b27f"
"minecraft:sandstone" = "#b1a172"
"minecraft:sandstone_stairs" = "#b1a172"
"minecraft:sandstone_slab" = "#b1a172"
"minecraft:smooth_sandstone" = "#b1a172"
"minecraft:polished_sandstone" = "#b1a172"
"minecraft:birch_log" = "#bdbcbb"
"minecraft:birch_trapdoor" = "#bdbcbb"
"minecraft:birch_planks" = "#bdbcbb"
"minecraft:polished_blackstone_bricks" = "#2e2d2e"
"minecraft:polished_blackstone_brick_slab" = "#2e2d2e"
"minecraft:polished_blackstone_brick_stairs" = "#2e2d2e"
"minecraft:polished_blackstone_slab" = "#2e2d2e"
"minecraft:polished_blackstone_stairs" = "#2e2d2e"
"minecraft:jungle_log" = "#5e4b39"
"minecraft:bamboo_slab" = "#b5b479"
"minecraft:bamboo_trapdoor" = "#b5b479"
"minecraft:birch_slab" = "#dbd0af"
"minecraft:birch_fence" = "#dbd0af"
"minecraft:birch_stairs" = "#dbd0af"
"minecraft:andesite" = "#9C9C9A"
"minecraft:polished_andesite" = "#9C9C9A"
"minecraft:polished_andesite_slab" = "#9C9C9A"
"minecraft:andesite_slab" = "#9C9C9A"
"minecraft:diorite" = "#DCDADD"
"minecraft:diorite_slab" = "#DCDADD"
"minecraft:diorite_stairs" = "#DCDADD"
"minecraft:polished_diorite" = "#DCDADD"
"minecraft:polished_diorite_slab" = "#DCDADD"
"minecraft:polished_diorite_stairs" = "#DCDADD"
"minecraft:soul_sand" = "#5e5044"
"minecraft:hay_block" = "#ad9936"
"minecraft:wheat" = "#F5DEB3"
"minecraft:cobweb" = "#d7d9d1"
"minecraft:gravel" = "#757575"
"minecraft:suspicious_gravel" = "#757575"
"minecraft:stone" = "#8E8E8E"
"minecraft:stone_button" = "#8E8E8E"
"minecraft:infested_stone" = "#8E8E8E"
"minecraft:smooth_stone" = "#8E8E8E"
"minecraft:stone_slab" = "#8E8E8E"
"minecraft:stone_stairs" = "#8E8E8E"
"minecraft:smooth_stone_slab" = "#9c9c9c"
"minecraft:stone_brick_slab" = "#8E8E8E"
"minecraft:stone_brick_wall" = "#8E8E8E"
"minecraft:infested_stone_bricks" = "#8E8E8E"
"minecraft:cracked_stone_bricks" = "#8E8E8E"
"minecraft:cobblestone" = "#5e5e5e"
"minecraft:dispenser" = "#5e5e5e"
"minecraft:cobblestone_stairs" = "#5e5e5e"
"minecraft:cobblestone_slab" = "#5e5e5e"
"minecraft:cobblestone_wall" = "#5e5e5e"
"minecraft:quartz_block" = "#d9d8d0"
"minecraft:quartz_pillar" = "#d9d8d0"
"minecraft:quartz_slab" = "#d9d8d0"
"minecraft:flowering_azalea_leaves" = "#bf62ab"
"minecraft:flowering_azalea" = "#bf62ab"
"minecraft:azalea_leaves" = "#57703a"
"minecraft:azalea" = "#57703a"
"minecraft:dripleaf" = "#73944e"
"minecraft:big_dripleaf" = "#73944e"
"minecraft:big_dripleaf_stem" = "#73944e"
"minecraft:small_dripleaf" = "#73944e"
"minecraft:spruce_log" = "#403a36"
"minecraft:iron_bars" = "#949494"
"minecraft:chain" = "#949494"
"minecraft:cyan_wool" = "#00a7d1"
"minecraft:cyan_bed" = "#00a7d1"
"minecraft:cyan_carpet" = "#00a7d1"
"minecraft:light_blue_wool" = "#54bff0"
"minecraft:light_blue_bed" = "#54bff0"
"minecraft:light_blue_carpet" = "#54bff0"
"minecraft:blue_wool" = "#1a2278"
"minecraft:blue_bed" = "#1a2278"
"minecraft:blue_carpet" = "#1a2278"
"minecraft:yellow_wool" = "#ffdd1f"
"minecraft:yellow_bed" = "#ffdd1f"
"minecraft:yellow_carpet" = "#ffdd1f"
"minecraft:orange_wool" = "#d67636"
"minecraft:orange_bed" = "#d67636"
"minecraft:orange_carpet" = "#d67636"
"minecraft:purple_wool" = "#783ac9"
"minecraft:purple_bed" = "#783ac9"
"minecraft:purple_carpet" = "#783ac9"
"minecraft:green_wool" = "#426117"
"minecraft:green_bed" = "#426117"
"minecraft:green_carpet" = "#426117"
"minecraft:brown_wool" = "#66421e"
"minecraft:brown_bed" = "#66421e"
"minecraft:brown_carpet" = "#66421e"
"minecraft:gray_wool" = "#8f8e8d"
"minecraft:gray_bed" = "#8f8e8d"
"minecraft:gray_carpet" = "#8f8e8d"
"minecraft:light_gray_carpet" = "#9ea2a3"
"minecraft:light_gray_bed" = "#9ea2a3"
"minecraft:light_gray_wool" = "#9ea2a3"
"minecraft:black_wool" = "#1a1a1a"
"minecraft:black_bed" = "#1a1a1a"
"minecraft:white_wool" = "#f5f5f5"
"minecraft:white_bed" = "#f5f5f5"
"minecraft:white_carpet" = "#f5f5f5"
"minecraft:red_wool" = "#a62424"
"minecraft:red_carpet" = "#a62424"
"minecraft:red_bed" = "#a62424"
"minecraft:pink_wool" = "#e899b1"
"minecraft:pink_bed" = "#e899b1"
"minecraft:podzol" = "#372215"
"minecraft:mud" = "#49382B"
"minecraft:mud_brick_slab" = "#735945"
"minecraft:packed_mud" = "#735945"
"minecraft:sea_pickle" = "#636b2f"
"minecraft:dead_tube_coral" = "#FF00FF"
"minecraft:dead_brain_coral" = "#FF00FF"
"minecraft:dead_bubble_coral" = "#FF00FF"
"minecraft:dead_fire_coral" = "#FF00FF"
"minecraft:dead_horn_coral" = "#FF00FF"
"minecraft:ancient_debris" = "#FF00FF"
"minecraft:dragon_head" = "#190f1f"
"minecraft:dragon_head_wall" = "#190f1f"
"minecraft:end_stone_bricks" = "#dde0a8"
"minecraft:end_stone_brick_slab" = "#dde0a8"
"minecraft:end_stone_brick_stairs" = "#dde0a8"
"minecraft:end_stone_brick_wall" = "#dde0a8"
"minecraft:end_stone" = "#dde0a8"
"minecraft:end_rod" = "#FFFEEB"
"minecraft:purpur_block" = "#b175bd"
"minecraft:purpur_slab" = "#b175bd"
"minecraft:purpur_stairs" = "#b175bd"
"minecraft:purpur_pillar" = "#b175bd"
"minecraft:chorus_plant" = "#5A3866"
"minecraft:chorus_flower" = "#F8D3FF"
"minecraft:end_portal_frame" = "#134a1c"
"minecraft:moss_carpet" = "#485c38"
"minecraft:moss_block" = "#485c38"
"minecraft:pink_petals" = "#F8C8DC"
"minecraft:clay" = "#BBC2C2"
"minecraft:sculk" = "#002B33"
"minecraft:sculk_vein" = "#00353E"
"minecraft:sculk_catalyst" = "#04343E"
"minecraft:sculk_sensor" = "#0B3B43"
"minecraft:sculk_shrieker" = "#0B3B43"
"minecraft:bubble_coral_block" = "#74429F"
"minecraft:bubble_coral_wall_fan" = "#74429F"
"minecraft:bubble_coral_fan" = "#74429F"
"minecraft:bubble_coral" = "#74429F"
"minecraft:horn_coral_block" = "#4760E9"
"minecraft:horn_coral_wall_fan" = "#4760E9"
"minecraft:horn_coral_fan" = "#4760E9"
"minecraft:horn_coral" = "#4760E9"
"minecraft:fire_coral_block" = "#FF4040"
"minecraft:fire_coral_wall_fan" = "#FF4040"
"minecraft:fire_coral_fan" = "#FF4040"
"minecraft:fire_coral" = "#FF4040"
"minecraft:tube_coral_block" = "#F88379"
"minecraft:tube_coral_wall_fan" = "#F88379"
"minecraft:tube_coral_fan" = "#F88379"
"minecraft:tube_coral" = "#F88379"
"minecraft:brain_coral_block" = "#FDBB32"
"minecraft:brain_coral_wall_fan" = "#FDBB32"
"minecraft:brain_coral_fan" = "#FDBB32"
"minecraft:brain_coral" = "#FDBB32"
"minecraft:pale_oak_leaves" = "#8A958F"
"minecraft:pale_moss_block" = "#8c999A"
"minecraft:prismarine" = "#419292"
"minecraft:prismarine_bricks" = "#419292"
"minecraft:dark_prismarine_slab" = "#316e6e"
"minecraft:dark_prismarine" = "#316e6e"
"minecraft:sea_lantern" = "#8dc7c3"
"minecraft:obsidian" = "#190f1f"
"minecraft:crying_obsidian" = "#190f1f"
"minecraft:crimson_trapdoor" = "#61173d"
"minecraft:warped_wart_block" = "#008585"
"minecraft:warped_roots" = "#008585"
"minecraft:nether_wart_block" = "#800606"
"minecraft:crimson_nylium" = "#800606"
"minecraft:crimson_roots" = "#800606"
"minecraft:nether_wart" = "#800606"
"minecraft:nether_brick_slab" = "#511515"
"minecraft:nether_bricks" = "#511515"
"minecraft:red_nether_bricks" = "#6b1010"
"minecraft:nether_brick_stairs" = "#511515"
"minecraft:basalt" = "#45484D"
"minecraft:smooth_basalt" = "#45484D"
"minecraft:polished_basalt" = "#45484D"
"minecraft:glass" = "#cce4ff"
"minecraft:glass_pane" = "#cce4ff"
"minecraft:green_stained_glass" = "#a6bfa8"
"minecraft:white_stained_glass" = "#ededed"
"minecraft:red_stained_glass" = "#8a5858"
"minecraft:pale_oak_slab" = "#d4d4d4"
"minecraft:redstone_block" = "#b81d06"
"minecraft:redstone_ore" = "#b81d06"
"minecraft:deepslate_redstone_ore" = "#b81d06"
"minecraft:gold_ore" = "#d4af37"
"minecraft:gold_block" = "#d4af37"
"minecraft:deepslate_gold_ore" = "#d4af37"
"minecraft:diamond_ore" = "#54d6ac"
"minecraft:deepslate_diamond_ore" = "#54d6ac"
"minecraft:yellow_terracotta" = "#997205"
"minecraft:glowstone" = "#e3cd8f"
"minecraft:tuff" = "#616161"
"minecraft:chiseled_tuff" = "#616161"
"minecraft:tuff_bricks" = "#616161"
"minecraft:chiseled_tuff_bricks" = "#616161"
"minecraft:tuff_brick_stairs" = "#616161"
"minecraft:tuff_brick_slab" = "#616161"
"minecraft:polished_tuff" = "#616161"
"minecraft:polished_tuff_slab" = "#616161"
"minecraft:lapis_ore" = "#303B95"
"minecraft:deepslate_lapis_ore" = "#303B95"
"minecraft:lapis_block" = "#303B95"
"minecraft:orange_concrete" = "#c95624"
"minecraft:red_sandstone_slab" = "#ad5f2b"
"minecraft:jungle_slab" = "#a88774"
"minecraft:jungle_planks" = "#a88774"
"minecraft:jungle_stairs" = "#a88774"
"minecraft:jungle_fence" = "#a88774"
"minecraft:brick_stairs" = "#8c4f2a"
"minecraft:brick_slab" = "#8c4f2a"
"minecraft:bricks" = "#8c4f2a"
"minecraft:acacia_slab" = "#ad704c"
"minecraft:acacia_planks" = "#ad704c"
"minecraft:acacia_trapdoor" = "#ad704c"
"minecraft:acacia_stairs" = "#ad704c"
"minecraft:dark_oak_slab" = "#47362E"
"minecraft:dark_oak_log" = "#47362E"
"minecraft:dark_oak_fence" = "#47362E"
"minecraft:dark_oak_stairs" = "#47362E"
"minecraft:dark_oak_trapdoor" = "#47362E"
"minecraft:dark_oak_planks" = "#47362E"
"minecraft:pumpkin" = "#b86500"
"minecraft:jack_o_lantern" = "#b86500"
"minecraft:soul_fire" = "#23e1e6"
"minecraft:soul_lantern" = "#23e1e6"
"minecraft:candle" = "#f8e1a8"
"minecraft:white_candle" = "#faf9e8"
"minecraft:red_candle" = "#ad4f51"
"minecraft:redstone_lamp" = "#b59f79"
"minecraft:granite_stairs" = "#945a37"
"minecraft:granite_slab" = "#945a37"
"minecraft:polished_granite" = "#a37052"
"minecraft:polished_granite_stairs" = "#a37052"
"minecraft:oak_log" = "#544741"
"minecraft:cobbled_deepslate_slab" = "#36373F"
"minecraft:cobbled_deepslate" = "#36373F"
"minecraft:cobbled_deepslate_wall" = "#36373F"
"minecraft:polished_deepslate" = "#36373F"
"minecraft:polished_deepslate_wall" = "#36373F"
"minecraft:polished_deepslate_stairs" = "#36373F"
"minecraft:deepslate_iron_ore" = "#615545"
"minecraft:deepslate" = "#36373F"
"minecraft:reinforced_deepslate" = "#36373F"
"minecraft:infested_deepslate" = "#36373F"
"minecraft:deepslate_bricks" = "#36373F"
"minecraft:deepslate_brick_stairs" = "#36373F"
"minecraft:chiseled_deepslate" = "#36373F"
"minecraft:deepslate_brick_slab" = "#36373F"
"minecraft:deepslate_tiles" = "#36373F"
"minecraft:deepslate_tile_slab" = "#36373F"
"minecraft:cracked_deepslate_tiles" = "#38393F"
"minecraft:cracked_deepslate_bricks" = "#38393F"
"minecraft:deepslate_tile_wall" = "#36373F"
"minecraft:deepslate_tile_stairs" = "#36373F"
"minecraft:cobbled_deepslate_stairs" = "#36373F"
"minecraft:polished_deepslate_slab" = "#36373F"
"minecraft:acacia_leaves" = "#004c00"
"minecraft:melon" = "#89b02e"
"minecraft:spruce_slab" = "#806e47"
"minecraft:stone_brick_stairs" = "#7f7f7f"
"minecraft:detector_rail" = "#a0a1a1"
"minecraft:red_sand" = "#7f3f1e"
"minecraft:brown_terracotta" = "#3b301f"
"minecraft:tall_seagrass" = "#669e59"
"minecraft:kelp" = "#003300"
"minecraft:kelp_plant" = "#003300"
"minecraft:spruce_trapdoor" = "#806e47"
"minecraft:spruce_stairs" = "#806e47"
"minecraft:bubble_column" = "#0c4b7c"
"minecraft:cornflower" = "#6495ed"
"minecraft:oak_stairs" = "#bfa56b"
"minecraft:farmland" = "#604c35"
"minecraft:oak_fence" = "#bfa56b"
"minecraft:snow" = "#e5e5e5"
"minecraft:snow_block" = "#e5e5e5"
"minecraft:fern" = "#447f26"
"minecraft:tall_grass" = "#447f26"
"minecraft:terracotta" = "#663516"
"minecraft:pot" = "#663516"
"minecraft:flower_pot" = "#663516"
"minecraft:decorated_pot" = "#663516"
"minecraft:rose_bush" = "#c82151"
"minecraft:iron_ore" = "#ada087"
"minecraft:grass_block" = "#447f26"
"minecraft:red_terracotta" = "#472a21"
"minecraft:red_glazed_terracotta" = "#472a21"
"minecraft:emerald_ore" = "#00674f"
"minecraft:emerald_block" = "#00674f"
"minecraft:dark_oak_leaves" = "#003a00"
"minecraft:glow_lichen" = "#96a08e"
"minecraft:lily_pad" = "#003f00"
"minecraft:blue_ice" = "#597fe5"
"minecraft:ladder" = "#bfa56b"
"minecraft:mossy_stone_brick_slab" = "#3b4a21"
"minecraft:mossy_stone_brick_stairs" = "#3b4a21"
"minecraft:infested_mossy_stone_bricks" = "#3b4a21"
"minecraft:water" = "#0c4b7c"
"minecraft:cherry_leaves" = "#f7cfe1"
"minecraft:spruce_planks" = "#806e47"
"minecraft:large_fern" = "#447f26"
"minecraft:wildflowers" = "#dbccff"
"minecraft:leaf_litter" = "#004c00"
"minecraft:short_grass" = "#447f26"
"minecraft:cut_sandstone" = "#c1b27f"
"minecraft:brown_mushroom_block" = "#695b5b"
"minecraft:polished_andesite_stairs" = "#ffffff"
"minecraft:ice" = "#7fb2e5"
"minecraft:short_dry_grass" = "#aa9966"
"minecraft:mossy_stone_bricks" = "#3b4a21"
"minecraft:dirt" = "#604c35"
"minecraft:rooted_dirt" = "#604c35"
"minecraft:azure_bluet" = "#ffffc8"
"minecraft:magma_block" = "#9c4814"
"minecraft:red_mushroom" = "#a6001c"
"minecraft:tall_dry_grass" = "#aa9966"
"minecraft:bush" = "#447f26"
"minecraft:stone_bricks" = "#7f7f7f"
"minecraft:granite" = "#4c4c4c"
"minecraft:bedrock" = "#565656"
"minecraft:rail" = "#a0a1a1"
"minecraft:lilac" = "#e1c4ff"
"minecraft:oak_trapdoor" = "#bfa56b"
"minecraft:powder_snow" = "#e5e5e5"
"minecraft:orange_tulip" = "#fd9954"
"minecraft:cactus" = "#547054"
"minecraft:oak_slab" = "#bfa56b"
"minecraft:oak_button" = "#bfa56b"
"minecraft:oak_pressure_plate" = "#bfa56b"
"minecraft:trial_spawner" = "#384e52"
"minecraft:vault" = "#384e52"
"minecraft:chest" = "#bfa56b"
"minecraft:barrel" = "#bfa56b"
"minecraft:mangrove_leaves" = "#003f00"
"minecraft:vine" = "#004c00"
"minecraft:cave_vines_plant" = "#004c00"
"minecraft:cave_vines" = "#004c00"
"minecraft:mossy_cobblestone_slab" = "#3b4a21"
"minecraft:red_mushroom_block" = "#a6001c"
"minecraft:light_gray_terracotta" = "#7f4f1e"
"minecraft:spruce_leaves" = "#193f19"
"minecraft:dandelion" = "#ffff00"
"minecraft:oxeye_daisy" = "#ffffc8"
"minecraft:allium" = "#e0b1e0"
"minecraft:bamboo" = "#197f19"
"minecraft:lava" = "#FF6E3A"
"minecraft:dirt_path" = "#604c35"
"minecraft:lily_of_the_valley" = "#e5ffe5"
"minecraft:sugar_cane" = "#447f26"
"minecraft:white_terracotta" = "#7f542b"
"minecraft:spruce_fence" = "#806e47"
"minecraft:packed_ice" = "#668ce5"
"minecraft:mycelium" = "#4d3f4b"
"minecraft:fire" = "#ffc045"
"minecraft:red_tulip" = "#e04c5b"
"minecraft:smooth_sandstone_slab" = "#c1b27f"
"minecraft:dead_bush" = "#aa8c59"
"minecraft:potted_dead_bush" = "#aa8c59"
"minecraft:mossy_cobblestone" = "#3b4a21"
"minecraft:copper_ore" = "#b87333"
"minecraft:deepslate_copper_ore" = "#b87333"
"minecraft:wall_torch" = "#ffc045"
"minecraft:pointed_dripstone" = "#806b5b"
"minecraft:coarse_dirt" = "#564430"
"minecraft:torch" = "#ffc045"
"minecraft:seagrass" = "#669e59"
"minecraft:coal_ore" = "#0E0E0E"
"minecraft:deepslate_coal_ore" = "#0E0E0E"
"minecraft:oak_planks" = "#bfa56b"
"minecraft:peony" = "#ffa6c8"
"minecraft:sunflower" = "#ffff00"
"minecraft:air" = "#000000" # red air for debugging, never want to see this
"minecraft:powered_rail" = "#a0a1a1"
"minecraft:poppy" = "#ff0000"
"minecraft:orange_terracotta" = "#7f4216"
"minecraft:netherrack" = "#632f2f"
"minecraft:dripstone_block" = "#806b5b"
"minecraft:brown_mushroom" = "#695b5b"
"minecraft:oak_leaves" = "#004c00"
"minecraft:amethyst_cluster" = "#8d63c7"
"minecraft:large_amethyst_bud" = "#7c56b0"
"minecraft:medium_amethyst_bud" = "#7c56b0"
"minecraft:small_amethyst_bud" = "#7350a4"
"minecraft:amethyst_block" = "#6a4a96"
"minecraft:budding_amethyst" = "#624496"
"minecraft:calcite" = "#b7b8b2"
